### PR TITLE
JC-200: update order status to completed if all items are delivered

### PR DESCRIPTION
**Pull request by jieunkxx**
JC-200: update order status to completed if all items are shipped

### CODE REVIEW

**Comment by inside1D** [comment]
Shouldn't orders become completed only after delivery instead of shipping?

**Comment by jieunkxx** [comment]
@inside1D
That's what this code does.
all items delivered => order completed
any item shipped => order shipped

**Comment by inside1D** [comment]
Oh OK. I was confused by the title

**Comment by jieunkxx** [comment]
@inside1D 
changed the title : )

**Review by armintalaie — APPROVED** [review]

**Pull request merged**
